version: '3'

# this docker-compose file is build only for test purposes

services:
  rocketchat:
    image: rocket.chat
    environment:
      - ADMIN_PASS=password
      - PORT=8080
      - ROOT_URL=http://localhost:8080
      - MONGO_URL=mongodb://mongo:27017/rocketchat
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 127.0.0.1:8080:8080

  mongo:
    image: mongo
    volumes:
     - /data/db
     - /dump
    command: mongod --smallfiles --oplogSize 128

  biblebot:
    build: .
    environment:
      - SPRING_DATASOURCE_USERNAME=biblebot
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:mysql://biblebotdb:3306/biblebot?autoReconnect=true&characterEncoding=utf8&useSSL=false
      - BIBLEBOT_INTEGRATION_ACTIVE=true
      - BIBLEBOT_INTEGRATION_HOST=biblebot
      - BIBLEBOT_INTEGRATION_PORT=8081
      - BIBLEBOT_API_HOST=rocketchat
      - BIBLEBOT_API_PORT=8080
      - BIBLEBOT_API_USER=admin
      - BIBLEBOT_API_PASSWORD=password
      - BIBLEREADINGPLAN_POSTSERVICE_CRON=0 0 * * * *
    links:
      - rocketchat
      - biblebotdb
    ports:
      - 127.0.0.1:8081:8081

  biblebotdb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: unusedpassword
      MYSQL_DATABASE: biblebot
      MYSQL_USER: biblebot
      MYSQL_PASSWORD: password
    ports:
      - 127.0.0.1:3306:3306